### ISSUE TITLE
Autocomplete?

### ISSUE THREAD

**Issue by GandalfSaxe** [gharlan/alfred-github-workflow#100]
Hi,

If I want to use e.g. `gh user/repo issues` and I start typing, and I see the right user/repo on the list, can I somehow use it instead of having to type out 100% of the rest?

Because if I press "enter" on the relevant repo, it just opens in my web browser. Arrow keys or modifier keys doesn't autocomplete.

**Comment by gharlan** [comment]
Use `TAB` key. :)

**Comment by GandalfSaxe** [comment]
Thanks! :)

(I did suspect it was a general Alfred question rather than specific for this workflow)
