### ISSUE TITLE
[Feature request] Limit search to just my repos

### ISSUE THREAD

**Issue by ryanjm** [gharlan/alfred-github-workflow#102]
99% of the time I'm just opening my own repos (or those of organizations I'm apart of). And while they do get bubbled to the top after a while, it'd be great if it wouldn't do the search across GH for any other matching repos. This would make it faster and give me more confidence visually that I'm selecting the right one (the list would only be one or two items long and I wouldn't need to read it).

In the case that I _do_ want to search globally, adding an additional attribute seems easy enough, such as `gh g {query}` for `global` search. I'd also be okay with this being a preference thing that you can choose to turn on or off. 

You could keep it simple too and ignore the global search open, such that if this preference option is turned on then you just couldn't do global searches. I'd be okay with that too. Like I said 99% of the time I'm just quickly opening my own repos.

**Comment by gharlan** [comment]
The workflow does not search globally for repos, it only searches your repos, repos of your organizations, and your starred repos.

Only with `gh s ...` it searches for other repos.
