### ISSUE TITLE
Doesn't Work in macOS 10.13.5 

### ISSUE THREAD

**Issue by Fanchao-Qi** [gharlan/alfred-github-workflow#103]
Hi,
I find that the corresponding items don't show in the drop-down menus of Alfred after I input the correct command. The Alfred version is 3.6.1. 

And here are the logs.

> [2018-07-06 22:42:16][input.scriptfilter] Queuing argument ''
[2018-07-06 22:42:16][input.scriptfilter] Script with argument '(null)' finished
[2018-07-06 22:42:16][input.scriptfilter] <?xml version="1.0"?>
<items><item uid="19b19ffc30caef1c9376cd2982992a59" autocomplete=" " valid="no"><icon>icon.png</icon><title>gh&#x2026;</title><subtitle>Search or type a command</subtitle></item></items>
[2018-07-06 22:42:16][input.scriptfilter] Queuing argument ' '
[2018-07-06 22:42:16][input.scriptfilter] Script with argument '(null)' finished
[2018-07-06 22:42:16][ERROR: input.scriptfilter] Code 255: Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: config in /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php:428
Stack trace:
#0 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(428): PDO->prepare('SELECT value FR...')
#1 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(97): Workflow::getStatement('SELECT value FR...')
#2 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(351): Workflow::getConfig('version')
#3 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredp in /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php on line 428
[2018-07-06 22:42:16][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: config in /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php:428
Stack trace:
#0 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(428): PDO->prepare('SELECT value FR...')
#1 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(97): Workflow::getStatement('SELECT value FR...')
#2 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(351): Workflow::getConfig('version')
#3 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredp in /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php on line 428
[2018-07-06 22:42:16][input.scriptfilter] Queuing argument ' j'
[2018-07-06 22:42:17][input.scriptfilter] Queuing argument ' jd'
[2018-07-06 22:42:17][input.scriptfilter] Script with argument '(null)' finished
[2018-07-06 22:42:17][ERROR: input.scriptfilter] Code 255: Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: config in /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php:428
Stack trace:
#0 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(428): PDO->prepare('SELECT value FR...')
#1 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(97): Workflow::getStatement('SELECT value FR...')
#2 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(351): Workflow::getConfig('version')
#3 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredp in /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php on line 428
[2018-07-06 22:42:17][input.scriptfilter] Script with argument '(null)' finished
[2018-07-06 22:42:17][ERROR: input.scriptfilter] Code 255: Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: config in /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php:428
Stack trace:
#0 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(428): PDO->prepare('SELECT value FR...')
#1 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(97): Workflow::getStatement('SELECT value FR...')
#2 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php(351): Workflow::getConfig('version')
#3 /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredp in /Users/qfc/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync Folder/Alfred.alfredpreferences/workflows/user.workflow.B7DE3A16-A14F-45C8-B8B1-B402DA474F9C/workflow.php on line 428

**Comment by benfogel** [comment]
Not sure if it'll work for your scenario, but I had the same error. I had to clear out the Alfred Workflow Data folder here `$HOME_DIRECTORY/Library/Application Support/Alfred 3/Workflow Data/$ID_FOR_GITHUB_WORKFLOW_APP`. Once I deleted the folder and re-ran the workflow, I was able to type commands successfully.

**Comment by Fanchao-Qi** [comment]
@benfogel It works! Thank you.

**Comment by mparent61** [comment]
This worked for me too, just wanted to say thanks!

**Comment by whosphp** [comment]
@benfogel Worked for me, Thanks
