### ISSUE TITLE
Feature Request: Initializing new repositories

### ISSUE THREAD

**Issue by ashco** [gharlan/alfred-github-workflow#106]
It would be handy if you could initialize a new repository from Alfred. Default settings (public, .gitignore) would be applied to the new repo. Command could be like the following:

`gh my new {repo name}`

**Comment by gharlan** [comment]
I've added `my repos new` sub command, which opens https://github.com/new.
(I do not want to actually create the repo, the workflow should only navigate to github pages etc.)
