### ISSUE TITLE
Not working on Alfred 4

### ISSUE THREAD

**Issue by SherlockedTxh** [gharlan/alfred-github-workflow#108]
<img width="605" alt="屏幕快照 2019-06-01 下午2 23 51" src="https://user-images.githubusercontent.com/10359238/58744749-3fee4580-8479-11e9-81bd-c98aaa22c327.png">
<img width="605" alt="屏幕快照 2019-06-01 下午2 29 39" src="https://user-images.githubusercontent.com/10359238/58744777-ba1eca00-8479-11e9-8a28-d4ed5e8f5c20.png">

once I type in "gh ",the following information pops out.tried deleting  $HOME_DIRECTORY/Library/Application Support/Alfred 3/Workflow Data/$ID_FOR_GITHUB_WORKFLOW_APP,didn't work.

debug:
[14:30:44.100] GitHub[Script Filter] Queuing argument ''
[14:30:44.242] GitHub[Script Filter] Script with argument '(null)' finished
[14:30:44.246] GitHub[Script Filter] <?xml version="1.0"?>
<items><item uid="19b19ffc30caef1c9376cd2982992a59" autocomplete=" " valid="no"><icon>icon.png</icon><title>gh&#x2026;</title><subtitle>Search or type a command</subtitle></item></items>
[14:30:44.539] GitHub[Script Filter] Queuing argument ' '
[14:30:44.684] GitHub[Script Filter] Script with argument '(null)' finished
[14:30:44.687] ERROR: GitHub[Script Filter] Code 255: loading content for https://api.github.com/repos/gharlan/alfred-github-workflow/releases/latest
[14:30:44.688] GitHub[Script Filter] Fatal error: Uncaught Error: Function name must be a string in /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/curl.php:74
Stack trace:
#0 /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/workflow.php(297): Curl->execute()
#1 /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/workflow.php(357): Workflow::requestCache('https://api.git...', Object(Curl), Object(Closure), true, 1440)
#2 /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/search.php(41): Workflow::checkUpdate()
#3 /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/search.php(609): Search::run('github', '', '0')
#4 {main}
  thrown in /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/curl.php on line 74
[14:30:44.692] ERROR: GitHub[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Uncaught Error: Function name must be a string in /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/curl.php:74
Stack trace:
#0 /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/workflow.php(297): Curl->execute()
#1 /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/workflow.php(357): Workflow::requestCache('https://api.git...', Object(Curl), Object(Closure), true, 1440)
#2 /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/search.php(41): Workflow::checkUpdate()
#3 /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/search.php(609): Search::run('github', '', '0')
#4 {main}
  thrown in /Users/friday/应用数据/Alfred.alfredpreferences/workflows/user.workflow.2806A536-1CD1-4BA4-A3AF-ABF410E158A3/curl.php on line 74

**Comment by tdeekens** [comment]
It seems to help removing `/Users/<your user>/Library/Application Support/Alfred 3/Workflow Data/de.gh01.alfred.github/`

**Comment by SherlockedTxh** [comment]
@tdeekens I tried that, still doesn't have search suggestions results.
<img width="605" alt="屏幕快照 2019-06-02 上午9 25 52" src="https://user-images.githubusercontent.com/10359238/58755535-7038f100-8518-11e9-88a9-d51463681aa5.png">

**Comment by SherlockedTxh** [comment]
I solved it by reinstalling Alfred and this workflow. This time I didn't use the old alfredpreferences, had to set everything up all over again. I guess something went wrong when Alfred 4 migrates my preferences.

**Comment by harmenjanssen** [comment]
For me the `de.gh01.alfred.github` file was also in `/Library/Application Support/Alfred/Workflow Data`, so I have removed it in two places, and re-installed the workflow. I didn't have to re-install Alfred 4.
That did the trick for me.

**Comment by gorexlv** [comment]
Any progress? :)

**Comment by hellojialee** [comment]
> For me the `de.gh01.alfred.github` file was also in `/Library/Application Support/Alfred/Workflow Data`, so I have removed it in two places, and re-installed the workflow. I didn't have to re-install Alfred 4.
> That did the trick for me.

@harmenjanssen Thank you for your hint. It works.

**Comment by nivv** [comment]
The fix does not work
