### ISSUE TITLE
Running with reduced permissions?

### ISSUE THREAD

**Issue by cameronsstone** [gharlan/alfred-github-workflow#111]
I just ran the login command, and the oauth request to github states:

> This application will be able to read and write all public and private repository data. This includes the following:
> - Code
> - Issues
> - Pull requests
> - Wikis
> - Settings
> - Webhooks and services
> - Deploy keys
> - Collaboration invites

Is there some way to run with reduced permissions? I mainly want to use it in a read-only manner.

**Comment by gharlan** [comment]
https://github.com/gharlan/alfred-github-workflow/issues/51

**Comment by cameronsstone** [comment]
I forgot to search closed issues. :-(

Thanks for the info. This is very surprising. :-(

Also, see dear-github issue 113 [GitHub's Permission System is Flawed](https://github.com/dear-github/dear-github/issues/113) for an attempt to consolidate the github feature request.

Apparently, the only option would be to [migrate to a github app](https://developer.github.com/apps/migrating-oauth-apps-to-github-apps/), but that seems like a large amount of work.

Thanks for taking the time to respond.
