### ISSUE TITLE
Cannot authenticate to GitHub with gh > login

### ISSUE THREAD

**Issue by burtino** [gharlan/alfred-github-workflow#112]
My github user has 2FA enabled. 

If I use the instructions `gh > login` it takes me to the personal access token page. 

If I try `gh login <Personal Access Key>` it also takes me right back to the page to create a personal access token. 

In short. Oauth login flow for `gh` doesn't seem to be working anymore. 

Any suggestions appreciated.

**Comment by higepon** [comment]
I have the exact same issue.

**Comment by ascot21** [comment]
I'm having issue too but typeing `gh > login` does nothing, doesn't even prompt me to start the login flow.

**Comment by gharlan** [comment]
Maybe try this: https://github.com/gharlan/alfred-github-workflow/issues/82#issuecomment-285797924

**Comment by ascot21** [comment]
@gharlan thanks, that fixed it. Wonder if there's a way to make the cache expire at a regular interval?

**Comment by gharlan** [comment]
Closing here. -> #82
