### ISSUE TITLE
better fuzzy search?

### ISSUE THREAD

**Issue by godbout** [gharlan/alfred-github-workflow#114]
any chance to improve the fuzzy search? like currently `gh tailw dash` wouldn't find `tailwindcss-dash-docset`, because of the hyphen.

i could check and do a PR if you're interested.

**Comment by gharlan** [comment]
`gh tailwdash` without the space should work.

**Comment by godbout** [comment]
sir, you are correct. it does work. just not the convention about fuzzy search, so it does feel a bit off. need to remember not to add a space especially for this workflow. hence opening this issue! if you feel it's not necessary, then please close it. else i can help. thanks! (i use your Workflow every day and love it.)

**Comment by gharlan** [comment]
The space does not fit in the current design. The space is the separator for the different command arguments, like in `gh foo/bar issues`. 
So in `gh tailw dash`, `tailw` would be the repo, and `dash` a sub command.

I always type without the space in fuzzy searches. For example here on github:

![Bildschirmfoto 2020-09-16 um 16 24 31](https://user-images.githubusercontent.com/330436/93350901-633d2f80-f839-11ea-862a-ed759ac40278.png)

**Comment by godbout** [comment]
fair enough. didn't know about the commands actually. but it's probably because i would never type the whole repo name! thanks.

**Comment by gharlan** [comment]
> but it's probably because i would never type the whole repo name! thanks.

I also never type the whole repo name, but I use tab for completion.

**Comment by godbout** [comment]
didn't even know we could use tab in Alfred 😂️ shift+tab actually. but i always use fuzzy search. anyways, good to know. learned something. thanks!
