### ISSUE TITLE
always not work after a period of use

### ISSUE THREAD

**Issue by alanhg** [gharlan/alfred-github-workflow#118]
![image](https://user-images.githubusercontent.com/9245110/101987849-7b560b00-3cd1-11eb-9741-39a033660704.png)

![image](https://user-images.githubusercontent.com/9245110/101987854-7f822880-3cd1-11eb-9a74-496a64acfda3.png)

current version: v1.6.2
Alfred version: v4.3

When I delete the cache and log in again, it will be available, but it fails after a while.

**Comment by gharlan** [comment]
closing in favor of #82
