### ISSUE TITLE
Workflow breaks on macOS 12 (Monterey)

### ISSUE THREAD

**Issue by snypelife** [gharlan/alfred-github-workflow#126]
Alfred version: 4.6 [1266]
OS version: macOS 12.0.1

<img width="255" alt="image" src="https://user-images.githubusercontent.com/1965406/139305337-2ccb6c7e-699c-4ce3-8bac-818d8e8dba74.png">

Because Apple removed the bundled PHP from  macOS 12, this workflow is now broken.

**Comment by codingwesley** [comment]
I found resolve method,

First, You need to upgrade Alfred to the latest version.
And Confirm your `brew config` has `HOMEBREW_PREFIX: /opt/homebrew`, is prefix path not in /opt/homebrew. you need change.

**Comment by AlexeyKorshun** [comment]
sorry but i still catch this issue, I installed php.

**Comment by codingwesley** [comment]
> sorry but i still catch this issue, I installed php.

Pls check your php bin position。Alfred only support 2 scene。 1. /usr/bin/php  2. /opt/homebrew/bin/php , Maybe you need confirm HOMEBREW_PREFIX

**Comment by AlexeyKorshun** [comment]
HOMEBREW_PREFIX=/usr/local , but it is default for intel base macbook
