### ISSUE TITLE
Cannot get issue list of the repository

### ISSUE THREAD

**Issue by adhrinae** [gharlan/alfred-github-workflow#129]
First of all, Thanks for the great work 👍 .

As a maintainer of some projects, I open the GitHub Issues page a lot.
Sometimes I want to open a specific issue number without opening the issues page because I remember the issue number.

Even though your workflow supports that feature, It seems not working at the moment.

## Environment
- x86 Mac (not tested on M1 mac yet)
- macOS 12.2.1
- PHP 8 is installed

## Steps of Reproduce
1. Type `gh` and any arbitrary repository. for example, this repo.
2. Type `Space` and `#`. and wait for any results to come out. Or Enter specific issue number like `#20`
3. Nothing happens

## Error log
```
Notice: Undefined property: stdClass::$pull_request in {MASKED}/{WORKFLOW_FOLDER}/search.php on line 405
```

**Comment by tobias-grasse** [comment]
I have the same issue. For a quick fix, change [line 405 of search.php](https://github.com/gharlan/alfred-github-workflow/blob/fbee857ff7bccbfbb6da70c620f0601e4e9555bb/search.php#L405) to `->icon(isset($issue->pull_request) ? 'pull-request' : 'issue')`. This prevents the undefined property error in case the given number is an issue and not a PR number. I'll open a PR right now 🙂 

@gharlan Thank you for this workflow!
