### ISSUE TITLE
[Feature Request] Add option to select browser to open in.

### ISSUE THREAD

**Issue by miclgael** [gharlan/alfred-github-workflow#134]
Thanks @gharlan for this workflow, I use it daily :) 

In my setup, I have modified `action.php:20` like so:

```php
exec('open -a Firefox\ Developer\ Edition '.$query);
```

To tell macOS to open my query in a specific browser. I thought this might be a cool / easily implementable feature.

**Comment by gharlan** [comment]
I do not want to add a config for this, sorry. I think default browser will fit for most people.
