### ISSUE TITLE
What is the file to adjust the icon?

### ISSUE THREAD

**Issue by Anber55** [gharlan/alfred-github-workflow#137]
I want to change the icon display after searching, how to change it

**Comment by gharlan** [comment]
Icons are here: https://github.com/gharlan/alfred-github-workflow/tree/main/icons
They are referenced in code on different places, e.g. here: https://github.com/gharlan/alfred-github-workflow/blob/3094696485f69579a2a38af9401e4ff1b30b7735/search.php#L326
