### ISSUE TITLE
Replicate App "in house" for privacy issues

### ISSUE THREAD

**Issue by rdohms** [gharlan/alfred-github-workflow#139]
Due to the lack of fine grained read-only repo access, this app will likely never be accepted in our internal GHEC instance.

One possibility I see is to replicate the app locally in our GHEC. Can you provide some more details, for example the OAuth callback, do you use it and what do you run on the server-side for this?

**Comment by gharlan** [comment]
The repo containing the oauth server is public now: https://github.com/gharlan/alfred-github-workflow-oauth

You can bypass the oauth flow by logging in with a personal access token (`gh login <token>` or `ghe login <token>`).
For GHE: https://github.com/gharlan/alfred-github-workflow#for-github-enterprise
