### ISSUE TITLE
Can't search in my organization private repos.

### ISSUE THREAD

**Issue by mous-alaa** [gharlan/alfred-github-workflow#141]
I work in an org and I can't view the repos under this org. If I open I can see the org. I assumed the org will be a user, but still can't search for the org.

**Comment by dhedegaard-digisense** [comment]
I had the same issue, fixed it by creating a PAT with the correct permissions instead of using OAuth.

**Comment by gharlan** [comment]
https://github.com/settings/connections/applications/2d4f43826cb68e11c17c

Does the org has a green checkmark there under `Organization access`?
Otherwise I think a org owner has to approve the oauth app.
