### ISSUE TITLE
Is This Project Still Maintained?

### ISSUE THREAD

**Issue by stdavis** [gharlan/alfred-github-workflow#145]
I absolutely LOVE this project! It's something that I use many times every workday. Thanks for your efforts on this!

I'm considering submitting a PR to add an additional shortcut (dependabot runs) and noticed that there hasn't been much activity on this project for some time. @gharlan Are you still working on this?

If this project is no longer maintained, is there anyone interested in working on a port of it to JavaScript using [alfy](https://github.com/sindresorhus/alfy)? I'd be willing to give it a go.

**Comment by gharlan** [comment]
I use the workflow every workday, too. So I will maintain it, but in slow mode. 

I would be happy about pull requests. And I will try to react more quickly in future. But at the same time, I don't want to promise too much. As long as it works for me, I sometimes leave it untouched for months.
