### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by stdavis** [gharlan/alfred-github-workflow#35]
After trying to apply the auto update I get this error message:
![image](https://cloud.githubusercontent.com/assets/1326248/5704865/4e257a32-9a32-11e4-9976-2911dac82d12.png)

I'm guessing that I can just uninstall and reinstall and it should be good but before I do I thought that you might want me to help debug the issue.

**Comment by gharlan** [comment]
Thanks for reporting this bug. It is fixed now.
But unfortunately you have to [download](http://gh01.de/alfred/github/github.alfredworkflow) manually the current version. Next time the update should work.

**Comment by stdavis** [comment]
No worries. Thanks for the great workflow. Use it constantly throughout the
day.

On Mon, Jan 12, 2015 at 11:10 AM, Gregor Harlan <notifications@github.com>
wrote:

> Thanks for reporting this bug. It is fixed now.
> But unfortunately you have to download
> <http://gh01.de/alfred/github/github.alfredworkflow> manually the current
> version. Next time the update should work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gharlan/alfred-github-workflow/issues/35#issuecomment-69615888>
> .
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by stdavis** [comment]
The latest update is failing for me again after downloading manually as you suggested above. :(

**Comment by stdavis** [comment]
In fact I just noticed that your download like (http://gh01.de/alfred/github/github.alfredworkflow) is broken as well. Maybe this is related?

**Comment by gharlan** [comment]
hmm, for me the link is working!?

**Comment by stdavis** [comment]
Looks like it was my work firewall. It's working for me now that I shut off VPN (both update and download link). Thanks for the awesome workflow. I use it constantly.
