### ISSUE TITLE
workflow consume too much of my cpu 

### ISSUE THREAD

**Issue by cmingxu** [gharlan/alfred-github-workflow#39]
php action.php > refresh-cache https://api.github.com/user?per_page=100,https://api.github.com/user/orgs?per_page=100,https://api.github.com/user/starred?per_page=100,https://api.github.com/user/subscriptions?per_page=100,https://api.github.com/user/repos?per_page=100,https://api.github.com/user/following?per_page=100

Here is what it does do from my `ps aux`

**Comment by gharlan** [comment]
Hmm. For performance reasons I use multi curl to fetch all required resources. Maybe I should limit the max. parallel requests. But I'm not sure if this is the problem.
I'm not able to reproduce the issue on my machine.
