### ISSUE TITLE
Use Personal API Access Tokens

### ISSUE THREAD

**Issue by espen** [gharlan/alfred-github-workflow#4]
The blog post says the tokens are like a password but I couldn't get it to work. Maybe it is a different way of authenticating?

https://github.com/blog/1509-personal-api-tokens

**Comment by sapegin** [comment]
I have the same errors when I try to login using the workflow. For some reason it has empty `$_ENV` array.

**Comment by gharlan** [comment]
Which OS X and Alfred version?

**Comment by sapegin** [comment]
OS X 10.10.2 and Alfred 2.6. Maybe there’s something wrong with my PHP config because I didn’t have any problems on my second Mac.

**Comment by gharlan** [comment]
Please update and try again. On one machine I had the same problem. Should be fixed now.
