### ISSUE TITLE
Search for issues by full text search

### ISSUE THREAD

**Issue by rhuss** [gharlan/alfred-github-workflow#45]
First of all, thanks for this awesome workflow !

It would be cool if one could directly search for issues from within Alfred, e.g. `gh user/project #` and then  part of an issue text. So, the same functionality as the autocomplete popup when you are editing an issue and type `#`.

I don't know whether this is feasible via the GitHub API, but for me it would be awesome because when writing mails or documentation, a quick lookup for an issue's URL and inserting it into the text would save quite some clicks.

**Comment by gharlan** [comment]
> but for me it would be awesome

For me, too. :+1: 
It is one of the next features I want to try to implement.

**Comment by rhuss** [comment]
Cool, thx ! :clap: :clap:

**Comment by gharlan** [comment]
With next release it is possible to search in issue titles via `user/repo #search`.

**Comment by rhuss** [comment]
Wow, that's awesome ! Thanks for the great work ...
