### ISSUE TITLE
Repository is not being found on refresh

### ISSUE THREAD

**Issue by rezzz-dev** [gharlan/alfred-github-workflow#46]
I created a Private repo; refreshed the local cache several times as well.

No matter what I do (even put in the full repo name) the repo does not appear in my list of results.  Any thoughts on why this may be happening?  Thanks so much!

**Comment by rezzz-dev** [comment]
Nvm - I uninstalled the workflow and re-installed it -- seems to be working now.

**Comment by gharlan** [comment]
> refreshed the local cache

Did you use the delete cache command of the workflow?
`gh > delete cache`
