### ISSUE TITLE
Private organisation repositories are not shown

### ISSUE THREAD

**Issue by maryokhin** [gharlan/alfred-github-workflow#49]
Hello, is it possible to tweak the API calls to Github to show also the private org. repos that I have access to? Would really make my work process more pleasant.

**Comment by cogell** [comment]
Have you logged in?

**Comment by maryokhin** [comment]
Yes, because I see my stuff, my org's public repos, but not the private ones.
<img width="542" alt="screenshot 2015-10-13 18 09 27" src="https://cloud.githubusercontent.com/assets/4390231/10460684/b6b65cee-71d5-11e5-8604-3f4fd040aba4.png">
<img width="551" alt="screenshot 2015-10-13 18 09 59" src="https://cloud.githubusercontent.com/assets/4390231/10460686/b9844558-71d5-11e5-9d4d-912342c57813.png">
<img width="541" alt="screenshot 2015-10-13 18 10 11" src="https://cloud.githubusercontent.com/assets/4390231/10460690/bbe2b64a-71d5-11e5-86b4-111c3ce0aca7.png">

**Comment by cogell** [comment]
hm! maybe try logging out and logging back in and making sure you provide all the necessary access

**Comment by maryokhin** [comment]
@cogell Sorry for the late response. Tried logging out/in and resetting cache, didn't help :(

**Comment by cogell** [comment]
@maryokhin bummer! perhaps there is a way for the orgo to restrict access. idk.

**Comment by gharlan** [comment]
Hmm strange, it is working for me (I see private org repos, I'm not the owner of the org, but have access to the repo).

**Comment by maryokhin** [comment]
I'll double check the access right for restrictions tomorrow.

**Comment by gharlan** [comment]
https://github.com/settings/applications

Open "alfred-github-workflow". Is the org listed under "Organization access"?

**Comment by maryokhin** [comment]
@cogell @gharlan 
thanks guys, it turned out to be the settings in https://github.com/settings/applications, I didn't even know those settings existed. I am happy code now :) Thanks for the tips and the awesome workflow :star2:
