### ISSUE TITLE
osascript: can't open default scripting component on OS X 10.11

### ISSUE THREAD

**Issue by cwagdev** [gharlan/alfred-github-workflow#50]
This workflow used to work great for me, now I am getting this error message when I debug it. The workflow has not worked since updating to 10.11. 

```
[INFO: alfred.workflow.input.scriptfilter] Processing output 'alfred.workflow.action.script' with arg 'https://github.com/REDACTED/REDACTED'
[ERROR: alfred.workflow.action.script] osascript: can't open default scripting component.
[INFO: alfred.workflow.action.script] Processing output 'alfred.workflow.output.notification' with arg ''
```

Any thoughts?

**Comment by cwagdev** [comment]
I've cross posted the issue in the Alfred forums: http://www.alfredforum.com/topic/8125-osascript-issues-in-1011-el-capitan/

**Comment by cwagdev** [comment]
Turns out my OS X install was fubar, re-installing on top of the existing install fixed the issue.

**Comment by brianpenghe** [comment]
I reinstalled and it worked.
