### ISSUE TITLE
Permissions: Write Access

### ISSUE THREAD

**Issue by dcalhoun** [gharlan/alfred-github-workflow#51]
When asked to authenticate, it seems this workflow requires access to "write" to repositories.

<img width="463" alt="github-permissions" src="https://cloud.githubusercontent.com/assets/438664/11409572/85046862-9386-11e5-9369-0e01c5fb0642.png">

1. What is the "write" permission used for?
2. Is it possible to use this workflow by _only_ approving "read" permissions?
3. Do you have any plans to allow approving _only_ "read" permissions?

Thanks!

**Comment by gharlan** [comment]
> 1. What is the "write" permission used for?

It's not used.
https://developer.github.com/v3/oauth/#scopes
Sadly there is no readonly scope for public and private repository data. That's the reason.

> 2. Is it possible to use this workflow by only approving "read" permissions?

Yes, but you will lose access to your private repos via this workflow.
You have to call this url: https://github.com/login/oauth/authorize?client_id=2d4f43826cb68e11c17c&state=1&scope=

> 3. Do you have any plans to allow approving only "read" permissions?

Yes, once there is a `repo_read` scope..

**Comment by gharlan** [comment]
PS: It bothers me, too!

**Comment by dcalhoun** [comment]
Ok. Thanks for all the information. That's a bummer that this is a limitation of the GitHub API. The write access is a little unnerving, particularly for repositories owned by organizations to which I belong.

I hope the GitHub team adds the `repo_read` scope. Do you know if there is a place to request such features or provide feedback for the GitHub API?

**Comment by gharlan** [comment]
> Do you know if there is a place to request such features or provide feedback for the GitHub API?

There is no special contact page for the api, so: https://github.com/contact

**Comment by fclaussen** [comment]
Is this still not possible?

**Comment by fabriziobertoglio1987** [comment]
https://circleci.com/blog/jan-4-2023-incident-report/
