### ISSUE TITLE
Is it possible to remove having to press space after entering the workflow with a hotkey?

### ISSUE THREAD

**Issue by nikitavoloboev** [gharlan/alfred-github-workflow#53]
The previous version of this workflow didn't have this issue. But now once updated I have to press space every time I want to run a query from my hotkey and this is something I wish I can change. I hope you can understand that.

Here is the video of what I mean : http://quick.as/3vbxcbR0O

Thank you and I hope there is a way to fix this.

**Comment by gharlan** [comment]
Yeah I understand that.
The reason for the change was this: #52 

So I'm not sure, what could be the best solution to make all happy.. ;)

**Comment by gharlan** [comment]
Added native hotkey support in recent release (1.4). Should work now.

**Comment by nikitavoloboev** [comment]
This is great. Thank you.

**Comment by gharlan** [comment]
Important note: In some environments they didn't work correctly. Should be fixed in current version 1.4.1.
