### ISSUE TITLE
Feature Request: can the workflow cache results so that repeat commands run fast

### ISSUE THREAD

**Issue by cogell** [gharlan/alfred-github-workflow#55]
When using `ghe` and sometimes `gh` it takes a while to load the commands -- including commands that remain static for months/yrs like `gh my pulls` etc

**Comment by jenius** [comment]
:+1: this would make a world of difference

**Comment by gharlan** [comment]
The workflow is already caching, and the cache is refreshing in background.
But unused cache is deleted after 30 days, so when you didn't use `gh` for 30 days, the next time will be slow. I will increase this to 100 days.

`gh my pulls` is static. But after typing `gh `, the workflow starts searching all your repos. And the workflow is waiting for the result before handling next input.

**Comment by cogell** [comment]
Ahh I see. So the issue is not caching but the command blocking on searching all the repos. Could the command be made to display current cache results immediately and run the search asynchronously in the background?

At best case this would provide all the expected commands and repos instantly. At worst case the user would see results for some of their repos/issues/pulls but not newly created ones until the async call completed. Either case, I suppose it would be best to surface some `fetching` dialogue to the user -- dunno how to do that. Perhaps stuff it in first option slot?

**Comment by gharlan** [comment]
> Could the command be made to display current cache results immediately and run the search asynchronously in the background?

It's already implemented this way. Only if there is no cache for the query type, then it is loaded synchronously before showing results.

> At worst case the user would see results for some of their repos/issues/pulls but not newly created ones until the async call completed.

.. until async call completed and hitting another key, because it is not possible to add async results to alfred.

**Comment by cogell** [comment]
ok kewl, thanks for helping me understand! I guess we can close this then.
