### ISSUE TITLE
Fuzzy search not finding repos

### ISSUE THREAD

**Issue by zebapy** [gharlan/alfred-github-workflow#57]
Perhaps it's due to too many repos because of the orgs but none of my actual repos are showing up. 

![screenshot 2016-03-30 19 55 45](https://cloud.githubusercontent.com/assets/2199845/14161405/6783702e-f6b1-11e5-82b2-312afdc2bd87.png)

This should most certainly be finding https://github.com/zebapy/react-redux-parse-server, should it not?

**Comment by gharlan** [comment]
hmm strange, is the behavior reproducible for you?

**Comment by zebapy** [comment]
I don't know if an update has affected this but it's working as expected now, thanks
