### ISSUE TITLE
I can't login using `gh > login`

### ISSUE THREAD

**Issue by AeroEchelon** [gharlan/alfred-github-workflow#58]
I've been using this workflow for the past few months or so and suddenly it has stopped working. I removed the previous installation and downloaded the new one. I can't login. Help?

![image](https://cloud.githubusercontent.com/assets/2360095/14745174/195c633c-0878-11e6-9b18-61042ffb301e.png)

**Comment by Geng-G-Razor** [comment]
I meet the same situation today, the workflow total lost efficacy, please help

**Comment by gharlan** [comment]
> I can't login.

What does happen when you hit enter on `gh > login`?
Maybe try to delete `/Users/<your user>/Library/Application Support/Alfred 2/Workflow Data/de.gh01.alfred.github/db.sqlite`.

**Comment by AeroEchelon** [comment]
Not sure – it has started working for me _magically_. I am currently logged in and can successfully do other commands like _gh > logout_.

**Comment by chmurph2** [comment]
I just ran into this.  I was only able to get things working again after deleting `/Users/<your user>/Library/Application Support/Alfred 2/Workflow Data/de.gh01.alfred.github/db.sqlite`

**Comment by chmurph2** [comment]
Corrupt database I guess.

**Comment by benleivian** [comment]
Ran into this issue today. Suddenly stopped working and `gh > logout` wouldn't even work. Deleting `de.gh01.alfred.github/db.sqlite` mentioned above did the trick. Never realized how much I use this workflow!

**Comment by benjie** [comment]
A note to anyone else who comes across this and has moved from Alfred 2 to Alfred 3 - don't forget to update the path above:

`/Users/<your user>/Library/Application Support/Alfred 3/Workflow Data/de.gh01.alfred.github/db.sqlite`

**Comment by schoenkaft** [comment]
Deleting `/Users/<your user>/Library/Application Support/Alfred 3/Workflow Data/de.gh01.alfred.github/db.sqlite` allowed me to login again. 

Login didn't work though. After disabling the macOS firewall however (no prompt to allow connection) and refreshing the callback URL, the callback came through and everything worked as expected.

**Comment by chmurph2** [comment]
I just ran into this issue again.  Deleting the sqlite DB fixed it.
