### ISSUE TITLE
Not able to login/use 

### ISSUE THREAD

**Issue by wcpines** [gharlan/alfred-github-workflow#59]
Since upgrading I haven't been able to actually use the workflow. Am I doing something wrong/missing something? 

Behavior:

![gh_alfred_error](https://cloud.githubusercontent.com/assets/11494834/14990134/22aa2988-1129-11e6-9399-4e296a344ade.gif)

**Comment by gharlan** [comment]
Hmm, there are some more users with this issues: https://github.com/gharlan/alfred-github-workflow/issues/58

Is it possible to logout? `gh > logout`

**Comment by wcpines** [comment]
😢 

![alfredtest](https://cloud.githubusercontent.com/assets/11494834/15046441/b041a0f2-12ad-11e6-8a68-5ace20ec132c.gif)

**Comment by gharlan** [comment]
the `>` is important.

**Comment by wcpines** [comment]
Whoops. Thank you. I was able to run that command. After about a minute, I got a desktop notification showing that I was successfully logged out.

**Comment by wcpines** [comment]
It looks like it's stuck running in the background:

```
CPU%  MEM%  VIRT   RES   PID USER        NI S     TIME+ Command 
99.8   0.3 2.48G 48.1M 12582 colby        0 R   0:52.53 php -f search.php -- github

```

**Comment by wcpines** [comment]
Tried https://github.com/gharlan/alfred-github-workflow/issues/58#issuecomment-214530517 and it seems to work :D

**Comment by gharlan** [comment]
hmm ok, it is hard to investigate because I do not have these problems here. Please report if it happens again.
