### ISSUE TITLE
[Feature Request] Maybe we need a search command by repo's name

### ISSUE THREAD

**Issue by johnwatsondev** [gharlan/alfred-github-workflow#60]
I used this wonderful workflow to search a project only by its name frequently. ( EVEN DON'T KNOW THE USER'S NAME )

So, Maybe the command of search by repo name like this:

```
gh s repo's name
```

Thanks for hard work.

**Comment by gharlan** [comment]
In next version you can search repos and users:
`gh s repo`
`gh s @user`
