### ISSUE TITLE
Doesn't work in Alfred 3

### ISSUE THREAD

**Issue by hudochenkov** [gharlan/alfred-github-workflow#62]
Workflow doesn't work in Alfred 3, because Alfred version is hardcoded in [workflow.php](https://github.com/gharlan/alfred-github-workflow/blob/master/workflow.php#L37):

```php
$dataDir = (isset($_ENV['HOME']) ? $_ENV['HOME'] : $_SERVER['HOME']) . '/Library/Application Support/Alfred 2/Workflow Data/' . self::BUNDLE;
```

After changing `Alfred 2` to `Alfred 3` workflow is working. Maybe there is a way to not hardcode Alfred version?

**Comment by rohanpai** [comment]
Same issue here... this extension is so much better than using GHs website so super looking forward to this :)
