### ISSUE TITLE
Request: My Repos

### ISSUE THREAD

**Issue by jacobkossman** [gharlan/alfred-github-workflow#64]
Can't believe this isn't one of the features. Hate having to go to my profile and then to my repos. Can we have "gh my repos" go to https://github.com/usernamehere?tab=repositories

thanks and good work on the workflow!

**Comment by seanvillalta** [comment]
Ha! I just happened to stumble here trying to get this workflow up and running again from my previous mac and saw you here purely by accident. I think this is a good request instead of having to _'gh @username repositories'_ just to get to your repos. Hopefully they implement it.

**Comment by jacobkossman** [comment]
https://github.com/jacobkossman/alfred-github-workflow

you can clone mine 👍
