### ISSUE TITLE
Search code in repository

### ISSUE THREAD

**Issue by liebe444ever** [gharlan/alfred-github-workflow#66]
Could I search code in repository and how? Thanks.

**Comment by gharlan** [comment]
At the moment it is not possible, but maybe I will add this feature.

**Comment by gharlan** [comment]
> At the moment it is not possible

To be more precise: You can open the code search from alfred:

1. type `gh your_query_to_find_repo`
2. hit `TAB`, it autocompletes the query to `gh user/full_repo_name `.
3. add your code search query, like `gh user/full_repo_name code_search_query`.
4. You get an item to open the repo search page with your query:

![screenshot 2016-12-07 23 15 59](https://cloud.githubusercontent.com/assets/330436/20988948/2f3e5696-bcd3-11e6-84fb-c2c2b10255f1.png)

Did you mean this? Or do you want to see the results of code search in alfred workflow?

**Comment by liebe444ever** [comment]
Yeah, it works, thanks a lot.
