### ISSUE TITLE
Private repo access issue

### ISSUE THREAD

**Issue by lxynox** [gharlan/alfred-github-workflow#67]
First and foremost, thanks for the awesome work, really nice and handy, love it 😃 

Here is a **tiny** issue, which if could be solved, would be even better. 
It's a **private** repo, which is visible once i logged in. And everything works just fine as i typed in `gh <usrname>`, a list of both public & private repos will be displayed, that is Good!

The problem comes here,
![screen shot 2016-09-04 at 5 00 14 pm](https://cloud.githubusercontent.com/assets/10333817/18233844/22c409e4-72c1-11e6-91b4-1e6c5dab03bb.png)

![screen shot 2016-09-04 at 5 03 22 pm](https://cloud.githubusercontent.com/assets/10333817/18233859/89484cc0-72c1-11e6-8024-80a1251b39cc.png)

The only input difference of below 2 pictures is an ` `(**empty space**). But if missing the space, the query and the auto completion of`<tab>` key will **FAIL** 😞 .

**Comment by gharlan** [comment]
If input is like `gh user/repo ` (**with space**), the workflow does not check existence of the repo, it directly shows the sub commands.

So that explains the difference, but not why it is missing in your repo list (without space). 
Please try to relogin (`gh > logout` -> `gh > login`).

**Comment by lxynox** [comment]
I did tried to relogin for some times, take a look at here
![screen shot 2016-09-18 at 12 37 25 pm](https://cloud.githubusercontent.com/assets/10333817/18617415/bb3bef26-7d9c-11e6-86fd-32fecdfb10a1.png)
![screen shot 2016-09-18 at 12 33 23 pm](https://cloud.githubusercontent.com/assets/10333817/18617387/487efe24-7d9c-11e6-9360-38cdfe4fec2e.png)
![screen shot 2016-09-18 at 12 33 44 pm](https://cloud.githubusercontent.com/assets/10333817/18617388/4a779984-7d9c-11e6-8c97-21beaee71d76.png)
I'm okay with this issue, good luck ; )

**Comment by gharlan** [comment]
That is strange.
If you search without a slash (`gh todomvc` etc.), the workflow searches through all your owned/starred/watched repos (an of your orgs).
When searching with slash (`gh lxynox/todo` etc.) the workflow searches through all repos of the exact user/org (`lxynox`). 
But it does not explain, why the repo is missing in the second case.

For me both cases work fine for private repos in organizations. I do not have private repos in my own account, so I can not test that.

**Comment by lxynox** [comment]
I digged into the source and found the codebase was just ___HUGE___, more than a **php newbie** would expect for a workflow. But really well organized with readability and quality in mind, just like this **awesome** app 👏 

Take a look at this snippet from [search.php line208](https://github.com/gharlan/alfred-github-workflow/blob/master/search.php)
```php
if ($isRepo) {
  $urls = array('/users/' . $queryUser . '/repos', '/orgs/' . $queryUser . '/repos');
} else {
  Workflow::requestApi('/user/orgs', $curl, function ($orgs) use ($getRepos) {
    foreach ($orgs as $org) {
       $getRepos('/orgs/' . $org->login . '/repos', 0);
    }
  });
  $urls = array('/user/starred', '/user/subscriptions', '/user/repos');
}
```

Let's say, we add a simple **conditional statement** like this, my problem seems would go away
```php
if ($isRepo) {
    if($queryUser != self::$user->login) {
        $urls = array('/users/' . $queryUser . '/repos', '/orgs/' . $queryUser . '/repos');
    } else {
        $urls = array('/user/repos'); // JUST grant the logged in user more 💎
    }
} else {
  // ......
}
```

Please feel free to correct me if i were wrong :D
