### ISSUE TITLE
Ranking scores organization > package

### ISSUE THREAD

**Issue by Moeriki** [gharlan/alfred-github-workflow#70]
Not sure if there is any logic for ranking the search results.

<img width="604" alt="screen shot 2016-09-30 at 14 10 53" src="https://cloud.githubusercontent.com/assets/38758/18991268/b7f6e198-8717-11e6-9898-503c07dabd4b.png">

When I search for `eslint` it ranks `eslint/espree` above `eslint/eslint` which I find incorrect.

Would it be a possibility to tweak the ranking the project's name has a higher weight.

**Comment by gharlan** [comment]
There is a ranking. I will try to improve the ranking for this case.

But also have in mind, that Alfred is learning your recently used results. They will be ranked to the top. You can disable this in Alfred preferences -> Advanced -> Learning.

**Comment by Moeriki** [comment]
Good point, thanks for clarifying that.

In this specific case though I have never (AFAIK / intentionally) opened Espree.
