### ISSUE TITLE
Missing `my repos` command

### ISSUE THREAD

**Issue by zillding** [gharlan/alfred-github-workflow#72]
v1.4.1

**Comment by zillding** [comment]
Following piece of code is missing in v1.4.1

https://github.com/gharlan/alfred-github-workflow/blob/master/search.php#L469-L475

**Comment by gharlan** [comment]
As you can see in [commit history](https://github.com/gharlan/alfred-github-workflow/commits/master), it was added after the last release (1.4.1).
I will be included in next release (which is planned for december).
