### ISSUE TITLE
Workflow doesn't response

### ISSUE THREAD

**Issue by clavichord93** [gharlan/alfred-github-workflow#76]
When I type 'gh <tab>', the workflow freezes and have no responses. Why is it?
![](http://ww3.sinaimg.cn/large/006tNbRwgw1fary76c6wwj30wy08aaau.jpg)

**Comment by clavichord93** [comment]
A reboot solve the issue.

**Comment by chuanxd** [comment]
I have same issue. But reboot Alfred still can't solve the issue.
version: 1.6.1

**Comment by clavichord93** [comment]
I rebooted my Mac.
