### ISSUE TITLE
Set a default repo to act on

### ISSUE THREAD

**Issue by Soleone** [gharlan/alfred-github-workflow#80]
### Background

The main reason I started looking for an Alfred workflow was the use case to quickly find a file via fuzzy search to be able to link to it in e.g. a new issue or pull request or in chat.

I can use the following and that's amazing, the workflow is really well made:

```
gh myusername/myreponame /some_folder_somewhere/some_partial_name
```

### Problem

But I am basically only using this for a single gigantic repo at work.

It would be great if I didn't have to type `myusername/myreponame` everytime (or wait for autocomplete to finish - in theory I have _lots_ of repos I'm participating in via my company's organization).

### Suggestion

Any way to set a **default repo** to act on, instead having to provide it every time? Is this possible right now or would you consider adding a configurable option for that?

**Comment by chmurph2** [comment]
Would it be possible to build your own workflow (that uses this workflow) to accomplish what you want?  It might be worth trying out Ritashugisha's [suggestions here](https://www.alfredforum.com/topic/3679-calling-a-workflow-from-another-workflow/) first.  HTH.

**Comment by Soleone** [comment]
interesting, thanks for the reply, i will give that a try soon and report back

**Comment by gharlan** [comment]
> Would it be possible to build your own workflow (that uses this workflow) to accomplish what you want? It might be worth trying out Ritashugisha's [suggestions here](https://www.alfredforum.com/topic/3679-calling-a-workflow-from-another-workflow/) first. HTH.

👍
