### ISSUE TITLE
Search in your stars and gists from alfred

### ISSUE THREAD

**Issue by jeandat** [gharlan/alfred-github-workflow#81]
Hi there,

Thanks for your workflow. Is it possible to search a gist or a starred repo from alfred ?
By reading your doc and testing it, it seems you can only go their respective page.
Am I right ?

**Comment by gharlan** [comment]
Currently it is not possible to search gists. But you can search your starred repos bei their names.

**Comment by gharlan** [comment]
I don't plan to implement gist search myself.
