### ISSUE TITLE
action.script doesn't understand the open location message

### ISSUE THREAD

**Issue by bnmnetp** [gharlan/alfred-github-workflow#86]
Hi,

Recently this workflow stopped working for me.  In the debug console I get the message:

```
[2017-04-25 09:41:54][ERROR: action.script] 0:48: execution error: "https://github.com/bnmnetp/CS330" doesn’t understand the “open location” message. (-1708)
```

I'm on the 10.12.5 beta

Thanks

**Comment by cookandy** [comment]
+1 - using Alfred `3.3.2 [818]` on OS X `10.12.5 Beta (16F60a)`

**Comment by anachlas** [comment]
I was able to work around it by changing line 20 of `action.php` to `    exec('osascript -e "tell application \"Safari\" to activate open location \"'.$query.'\""');`

**Comment by cookandy** [comment]
thanks - that worked for me too!

**Comment by gharlan** [comment]
Thanks for reporting and finding a solution.
But it would force Safari, so I will use this command instead: `open "<url>"` 
I think it will work, too (I can not test it with 10.12.5 Beta).

**Comment by anachlas** [comment]
Yeah I know its not a good long term solution, unfortunately I tested `open "<url>"` and got the same error:
`execution error: "https://github.com/stablekernel/aqueduct" doesn’t understand the “open” message. (-1708)`

**Comment by gharlan** [comment]
Does the issue still exist with beta 5?

**Comment by anachlas** [comment]
Yeah I updated to `10.12.5 Beta (16F71b)` just now and both `open` and `open location` still aren't working.

**Comment by gharlan** [comment]
Is it possible to open url directly from terminal? `open https://github.com`

**Comment by anachlas** [comment]
Yes that still works.

**Comment by anachlas** [comment]
Changing the line to `    exec("open $query");` works! 🎉
