### ISSUE TITLE
Workflow doesn't work with autoupdate activated

### ISSUE THREAD

**Issue by xilopaint** [gharlan/alfred-github-workflow#87]
If I have autoupdate activated `gh` prompts me to update the workflow and I have no
other options besides these three:

![screen shot 2017-05-07 at 17 07 51](https://cloud.githubusercontent.com/assets/11052366/25784678/b85ecc54-3347-11e7-9d84-cad5e01e07f4.png)

Is that possible it's happening because you forgot to updated the version?

![screen shot 2017-05-07 at 4 55 18 pm](https://cloud.githubusercontent.com/assets/11052366/25784730/78da2320-3348-11e7-845a-53895df644d8.png)

**Comment by gharlan** [comment]
You are absolutely true! I've updated the version and replaced the download now.
So it should be fixed after selecting `> update` once again.
