### ISSUE TITLE
Having trouble with the GHE side of the workflow

### ISSUE THREAD

**Issue by BenGitsCode** [gharlan/alfred-github-workflow#90]
I set my url `https://git.generalassemb.ly/ga-wdi-boston/` and my access token with the repo scope but this is the behavior when I try any GHE commands. This is mostly me typing ghe + enter. 

https://cl.ly/lFHS

I'm assuming user error on the setup but I can't figure out what the issue is.

**Comment by BenGitsCode** [comment]
I've referenced  #78 so far and it turns out that <enterprise>/api/v3/user?access_token=<token> shows a 404 🤔

**Comment by BenGitsCode** [comment]
I just redid the steps and now I'm getting the data from the token, but ghe still just prompts me to login. (i did receive the login successful notification on the initial attempt.

**Comment by BenGitsCode** [comment]
I'm still getting the same issues with this workflow. Is it possible the custom domain is causing problems. Just tried again since it's been a while and even though I get a successful login this is what I get when trying to access GHE repos. 

<a href="https://cl.ly/2U2o0i171b1z" target="_blank"><img src="https://d1ax1i5f2y3x71.cloudfront.net/items/3n0h2Y0j2h2O3B0h3v0H/Screen%20Recording%202017-11-02%20at%2010.40%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by gharlan** [comment]
Is anybody else using this workflow with github enterprise and can help here?
I do not have access to any github enterprise instance.
