### ISSUE TITLE
Solve: Update to v1.6.1 not working issue

### ISSUE THREAD

**Issue by chuanxd** [gharlan/alfred-github-workflow#95]
Alfred version `3`
When I update to new version `v1.6.1` the github workflow not working.

### To Remove one folder
```
/Users/<your user>/Library/Application Support/Alfred 3/Workflow Data/de.gh01.alfred.github/
```
### Reinstall github workflow
Login github again.
```sh
gh > login
```

**Comment by WillBeethoven** [comment]
@chuanxd It works! How did you debug it?

**Comment by jtr109** [comment]
Thanks a lot. Is that some issues in the database?

**Comment by jtr109** [comment]
Unfortunately, the issue appear again after using your solution.

Hope the issue can be solved soon.

![image](https://user-images.githubusercontent.com/13946679/33486878-7a1a3512-d6e6-11e7-9777-70d541df0fb0.png)

**Comment by ParsifalC** [comment]
it works for me!

**Comment by gregoralbrecht** [comment]
The solution in the first comment worked perfectly but the issues keeps popping up. I had to delete this folder 4 times in the last two days, so it's not really a permanent solution. Does anyone have any news on this?

**Comment by chuanxd** [comment]
@gregoralbrecht What is your alfred version and github workflow version ?
I don't have any problem again.

**Comment by gregoralbrecht** [comment]
@chuanxd It's the newest release of the workflow, `v1.6.2` and the newest Alfred `3.6.1`. Hasn't happened for a couple days now, fingers crossed!
