### ISSUE TITLE
Clone not working as expected

### ISSUE THREAD

**Issue by matt-James** [gharlan/alfred-github-workflow#96]
expected: gh user/repo clone (eg: gh https://github.com/reactjs/react-codemod clone) should clone repo

actual: typing in _gh https://github.com/reactjs/react-codemod clone_ and hitting enter seems to have no effect

**Comment by snwflake** [comment]
`gh user/repo clone` -> cmd + return
Not sure why the modifier is there, that doesn't make much sense.

**Comment by dimart** [comment]
@matt-James have you found a way to fix that?
cmd + return just copies the URL

**Comment by gharlan** [comment]
Hitting enter opens `github-mac://openRepo/...`.
It seems Github has changed the url to `x-github-client/openRepo/...`. Will change it, too.

The url is handled by GitHub Desktop and Tower. Maybe by other git clients, too.

**Comment by snwflake** [comment]
I don't think anybody here expected you to need some gui git client for that to work properly...
